const Error = {
    NOT_FOUND: "NOT_FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    AUTHENTICATION_FAILLED: "AUTHENTICATION_FAILLED",
    NOT_UNIQUE: "NOT_UNIQUE",
    ER_DUP_ENTRY: "ER_DUP_ENTRY",
    LOGIN_FAILED: "LOGIN_FAILED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR",
    ALREADY_ASSIGNED: "ALREADY_ASSIGNED"
}

module.exports = Error;